name: build npm

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build-npm-and-docs:
    runs-on: ubuntu-latest
    steps:
      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: clone repo
        uses: actions/checkout@v3

      - name: deno-task test
        run: deno task test

      - name: deno-task build-npm
        run: deno task build-npm

      - name: create npm branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: npm
          FOLDER: npm
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: deno-task build-docs
        run: deno task build-docs

      - name: deploy github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
